### ISSUE TITLE
What are the guidelines / rules for photos of red pandas?

### ISSUE THREAD

**Issue by huy-vuong** [wwoast/redpanda-lineage#103]
I take photos of red pandas at two of the zoos a lot on the side for fun and would love to contribute them to this dataset, but what are the rules or guidelines for contributed photos?

**Comment by wwoast** [comment]
There's not a good written policy for this yet, but here's what I've been doing:
* I do try to ask for permission first before linking to photos. So if you want to add your own photos, I assume it's just fine :+1:
* I like linking to Instagram photos when possible, just because it seems like their daily panda content dwarfs the rest of the Internet! When I do, I use the `size=m` versions which are small-ish, no bigger than 300px across, relatively quick to load. For your own photos, you can use whatever size you wish, but the layout will cap the display width at 400px for non-mobile layouts.
* The photos in the existing panda entries are intended as _identifying_ photos of individual animals. So you'll notice they only include a single animal in the shot, so it's not confusing which animal is being referred to. I'm working on "detailed" panda sections that will have plenty of room for social or action-ish photo sets, so there will be room for other interesting types of photos soon!
* There's not an upper limit on the number of _identifying_ photos per animal, but the swipe/click to navigate thing really means that more than 50 or so images for a single animal is kinda ridiculous. Again, the "detailed" panda sections will hopefully make this more sensible.

**Comment by wwoast** [comment]
Going to keep this ticket open as a reminder to formalize the policy for photo contributions.

**Comment by wwoast** [comment]
@huy-vuong -- if there are any zoos I might add to make it easier for you or your friends to contribute photos, let me know. :+1:

**Comment by huy-vuong** [comment]
Thanks @wwoast! Admittedly, it's finding image hosting that's my main blocker right now. ^_^; I have a Flickr, but I don't think it handles hotlinking as nicely. I just need to get around making an Instagram account and I should be able to link a few photos here!
