### ISSUE TITLE
Red panda map based on this dataset

### ISSUE THREAD

**Issue by DylanMoriarty** [wwoast/redpanda-lineage#193]
Howdy do,

Over the past two weeks I put together a web map based on this data that I think ya'll might get a kick out of: https://dylanmoriarty.github.io/red-panda-map/

I've wanted to put this together for awhile now, but hadn't been able to get any decent global datasets for where Red Pandas are. So thanks a whole lot for putting this together!

Right now it doesn't automatically update to your most recent additions, but hoping to add that on at a later point. Completely missed that you have lat/lngs for the zoos already built into the database, so might not be too hard to setup.

Cheers!

**Comment by wwoast** [comment]
This looks fantastic! The style and the artwork are very cute. Cheers for creating and sharing your _Red Pandas of the World_... I should add this to the links section of https://redpandafinder.com at the very least!

The lat/long stuff hasn't been in the redpanda-lineage dataset for too long and is thanks to some support from https://github.com/neofluar/redpandas :heart:

I noticed for a particular panda _Zayn_ that it's listing her location as the Dublin Zoo, not the Moscow Zoo where she lives now. This issue might be caused by building your `panda-to-json.js` from the `location.N` values, which list all prior zoos a panda has lived at, and not the `zoo` values which list the most recent zoo for the animal.

The zoo data from this project is indeed very incomplete for India, China, Nepal, and Europe, and there are many animals missing from the zoos in America. Zoo studbooks have much of this data, but public copies of them are nearly 2 years out-of-date. On top of that, for some regions (especially China) studbook data is unreliable, incomplete, or unavailable. Since I try to obtain photos of each panda, I think approaching 100% will just be a slow process.

The map is functional on my iPhone but it's easy to pinch/zoom the UI into a messy place, which is pretty par for the course on mobile. I'd love to make a usable family tree and global map for https://redpandafinder.com, but mobile UX is such a struggle.

Again, thank you and much props for making this!
Justin

**Comment by wwoast** [comment]
https://github.com/wwoast/redpanda-lineage/commit/7f2ff4ceb1bef375c7035117e4b8eeea90efab99
